[package]
name = "actix-web-demo"
version = "0.1.0"
authors = ["YinYin Chiu <cychiuae@connect.ust.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
